version: "2"
services:
  title-fingerprint-db:
    build: ./title-fingerprint-db
    volumes:
      - ./db:/data/db
    ports:
      - 8004:80
    stop_grace_period: 999h
    networks:
      identifier:
        ipv4_address: 172.13.5.2
networks:
  identifier:
    driver: bridge
    ipam:
      config:
        - subnet: 172.13.5.0/24
          gateway: 172.13.5.1